#ifndef HU_SELFTEST_H
#define HU_SELFTEST_H

#ifndef HU_AMALGAMATED
#    include <hu.h>
#endif

HU_STATIC_ASSERT(HU_SIZEOF_SHORT == sizeof(short));
HU_STATIC_ASSERT(HU_SIZEOF_INT == sizeof(int));
HU_STATIC_ASSERT(HU_SIZEOF_LONG == sizeof(long));
HU_STATIC_ASSERT(HU_SIZEOF_LONG_LONG == sizeof(long long));
HU_STATIC_ASSERT(HU_SIZEOF_LONG_LONG == 8);
HU_STATIC_ASSERT(HU_SIZEOF_PTR * 8 == HU_BITS);
HU_STATIC_ASSERT(HU_SIZEOF_PTR == sizeof(void *));

#if HU_DATA_MODEL_IP16_P
HU_STATIC_ASSERT(HU_SIZEOF_SHORT == 2);
HU_STATIC_ASSERT(HU_SIZEOF_INT == 2);
HU_STATIC_ASSERT(HU_SIZEOF_LONG == 4);
HU_STATIC_ASSERT(HU_SIZEOF_PTR == 2);
#elif HU_DATA_MODEL_LP32_P
HU_STATIC_ASSERT(HU_SIZEOF_SHORT == 2);
HU_STATIC_ASSERT(HU_SIZEOF_INT == 2);
HU_STATIC_ASSERT(HU_SIZEOF_LONG == 4);
HU_STATIC_ASSERT(HU_SIZEOF_PTR == 4);
#elif HU_DATA_MODEL_ILP32_P
HU_STATIC_ASSERT(HU_SIZEOF_SHORT == 2);
HU_STATIC_ASSERT(HU_SIZEOF_INT == 4);
HU_STATIC_ASSERT(HU_SIZEOF_LONG == 4);
HU_STATIC_ASSERT(HU_SIZEOF_PTR == 4);
#elif HU_DATA_MODEL_LLP64_P
HU_STATIC_ASSERT(HU_SIZEOF_SHORT == 2);
HU_STATIC_ASSERT(HU_SIZEOF_INT == 4);
HU_STATIC_ASSERT(HU_SIZEOF_LONG == 4);
HU_STATIC_ASSERT(HU_SIZEOF_PTR == 8);
#elif HU_DATA_MODEL_LP64_P
HU_STATIC_ASSERT(HU_SIZEOF_SHORT == 2);
HU_STATIC_ASSERT(HU_SIZEOF_INT == 4);
HU_STATIC_ASSERT(HU_SIZEOF_LONG == 8);
HU_STATIC_ASSERT(HU_SIZEOF_PTR == 8);
#elif HU_DATA_MODEL_ILP64_P
HU_STATIC_ASSERT(HU_SIZEOF_SHORT == 2);
HU_STATIC_ASSERT(HU_SIZEOF_INT == 8);
HU_STATIC_ASSERT(HU_SIZEOF_LONG == 8);
HU_STATIC_ASSERT(HU_SIZEOF_PTR == 8);
#elif HU_DATA_MODEL_SILP64_P
HU_STATIC_ASSERT(HU_SIZEOF_SHORT == 8);
HU_STATIC_ASSERT(HU_SIZEOF_INT == 8);
HU_STATIC_ASSERT(HU_SIZEOF_LONG == 8);
HU_STATIC_ASSERT(HU_SIZEOF_PTR == 8);
#endif

#if HU_ARCH_X86_P || HU_ARCH_AVR_P || HU_ARCH_RISCV_P
HU_STATIC_ASSERT(HU_LITTLE_ENDIAN_P);
#endif

#if HU_OS_LINUX_P
HU_STATIC_ASSERT(HU_OBJFMT_ELF_P);
#elif HU_OS_APPLE_P
HU_STATIC_ASSERT(HU_OBJFMT_MACHO_P);
#endif

#endif
